import "./globals.css";
import { Toaster} from "sonner";

export const metadata = {
  title: "Sleep App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-[#242933]">
        {children}
        <Toaster richColors="true" position="top-right"/>
      </body>
    </html>
  );
}
