import "./globals.css";

export const metadata = {
  title: "Sleep App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-[#242933]">
        {children}
      </body>
    </html>
  );
}
